ARG BASE_IMAGE=hooyu/mindnlp-latest:1
FROM ${BASE_IMAGE}
WORKDIR /app
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=/app
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY . /app
RUN chmod +x /app/Dockerfiles/entrypoint.sh /app/Dockerfiles/start-ray-worker.sh
ENTRYPOINT ["/app/Dockerfiles/entrypoint.sh"]
